__init__.py
from flask_sqlalchemy import SQLAlchemy
from flask import Flask
from flask_login import LoginManager
from flask_mail import Mail
import os
from itsdangerous import URLSafeTimedSerializer
import configs
from dotenv import load_dotenv
'''from dbssh import create_ssh_tunnel'''

'''tunnel = create_ssh_tunnel()'''
load_dotenv("creds.env")
conn_credentials = os.environ.get("myql_creds")
app_key = os.environ.get("app_key")
serializer_key = os.environ.get("serializer_key")
db = SQLAlchemy()
mail = Mail()
serializer = URLSafeTimedSerializer(serializer_key)

def create_app():
    """Construct the core application."""
    app = Flask(__name__)
    app.config.from_object(configs.devConfig)
    db.init_app(app)
    mail.init_app(app)
    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'login'

    with app.app_context():
        from routes import routes  # Import routes
        app.register_blueprint(routes)
        db.create_all()  # Create database tables for our data models
        app.secret_key = app_key
        return app

app.py
from __init__ import create_app

app = create_app()

'''from user_model import User
from routes import routes

load_dotenv("creds.env")
key = os.environ.get("key")
conn_credentials = os.environ.get("psql_credss")

Base = declarative_base()
from user_model import db
db.init_app(app)
db.create_all()
app.register_blueprint(routes)
'''

if __name__ == "__main__":
    app.run()

routes.py
from flask import Flask, request, redirect, render_template, Blueprint, flash, url_for
from flask_login import login_user, logout_user, login_required, current_user
from twilio.twiml.messaging_response import MessagingResponse
from register import register_user
from login import authenticate_user
#from confirm_mail import confirm_the_email
from user_model import User
from __init__ import db, serializer
from datetime import datetime
routes = Blueprint('routes', __name__)

@routes.route('/')
@routes.route('/login', methods=["GET", "POST"])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        print(password, email)

        return authenticate_user(email, password)
        #login_user()
    return render_template('index.html', title='login')


@routes.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        print(password, email)

        registration_result = register_user(email, password)

        if registration_result is True:
            flash('Please click the link in your email to confirm your account')
            return redirect(url_for('routes.login'))

        else:
            flash(f'{registration_result}')

    return render_template('register.html', title='register')

@routes.route('/confirm_email/<token>', methods=['GET', 'POST'])
def confirm_email(token):
    if request.method == 'GET':
        try:
            # Verify the token and get the email
            email = serializer.loads(token, salt='confirm-email') # max_age=3600
        except:
            flash('Invalid or expired token')
            return render_template('index.html', title='login')
        user = User.query.filter_by(email=email).first()
        if user:
            user.confirmed = True
            user.confirmed_on = datetime.utcnow()
            db.session.commit()
            flash('Email confirmed')
            return render_template('index.html', title='login')
        else:
            flash('User not found')

    return render_template('index.html', title='login')

@routes.route('/home')
@login_required
def home():
    logout_user()
    return render_template('home.html', title='home')

@routes.route("/sms", methods=['POST'])
def sms():
    # Get the incoming message
    message_body = request.form["Body"]
    print(message_body)
    # Create a Twilio response object
    resp = MessagingResponse()

    # Add a message to the response
    resp.message(
        "Please contact Stephen or Nicole for questions. Stephen can be reached at 832-341-9281, and Nicole at 713-417-3996")

    return str(resp)

templates/index.html
<!DOCTYPE html>
<html>
<head>
  <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/bulma.min.css') }}" rel="stylesheet">
  <title>{{title}}</title>
</head>
<body>
  <section class="section">
    <div class="container">
      <h1 class="title is-1 has-text-centered">{{title}}</h1>
      <div class="columns is-centered">
        <div class="column is-one-quarter">
          <form id="login-form" action="{{ url_for('routes.login')}}" method="POST" class="box">
            <div class="field">
              <label class="label">Email:</label>
              <div class="control">
                <input type="email" name="email" required class="input is-one-third">
              </div>
            </div>
            <div class="field">
              <label class="label">Password:</label>
              <div class="control">
                <input type="password" name="password" required class="input is-one-third">
              </div>
            </div>
            <div class="field is-grouped is-grouped-centered">
              <div class="control">
                <input type="submit" value="Submit" class="button is-link">
              </div>
              <div class="control">
                <a id="register" href="{{ url_for('routes.register')}}" class="button is-link">Register</a>
              </div>
            </div>
          </form>
        </div>
      </div>
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <div class="notification is-danger">
            {% for message in messages %}
              {{ message }}
            {% endfor %}
          </div>
        {% endif %}
      {% endwith %}
    </div>
  </section>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html>
  <head>
    <link href="{{ url_for('static', filename='css/bulma.min.css') }}" rel="stylesheet">
    <title>{{ title }}</title>
  </head>
  <body>
    <section class="section">
      <div class="container">
        <div class="columns is-centered">
          <form id="register" action="{{ url_for('routes.register')}}" method="POST" class="box is-one-quarter">
            <div class="field">
              <label class="label">Email:</label>
              <div class="control">
                <input type="email" id="email" name="email" required class="input is-one-third">
              </div>
            </div>
            <div class="field">
              <label class="label">Password:</label>
              <div class="control">
                <input type="password" id="password" name="password" required class="input is-one-third">
              </div>
            </div>
            <div class="field">
              <label class="label">Confirm Password:</label>
              <div class="control">
                <input type="password" id="confirm_password" name="confirm_password" required class="input is-one-third">
              </div>
            </div>
            <div class="field is-grouped is-grouped-centered">
              <div class="control">
                <input type="submit" value="Register" class="button is-link">
              </div>
            </div>
          </form>
        </div>
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            <div class="notification is-danger">
              {% for message in messages %}
                {{ message }}
              {% endfor %}
            </div>
          {% endif %}
        {% endwith %}
      </div>
    </section>
  </body>
</html>